language: python

services:
  - redis-server
  - elasticsearch

before_script:
  - sleep 10

python:
    - "3.6"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=unit

install:
    - make setup

script:
  - make $TEST_TYPE
